### ISSUE TITLE
Heavy usage of DllCallbackRegister can result in crash

### ISSUE THREAD

**Issue by genius257** [genius257/AutoItObject-Internal#5]
```AutoIt3
#include "AutoItObject_Internal.au3"

For $i=0 To 10000
    ConsoleWrite($i&@CRLF)
    $o = IDispatch()
Next
```

On my test PC, around "8958" AutoIt crashes.
`AutoIt3.exe ended.rc:-1073741819`

The issue itself is with AutoIt3 itself, but AutoItObject-Internal can avoid it, mostly.

A solution may be to change the way the default parameters in the IDispatch function are used. Instead of calling DllCallbackRegister every time, the defaults should only be created once internally in the function `Local Static $...` and used that way instead.

To also reduce this issue for cases with custom parameters, maybe check if variable is int (Int32 is the return type from a DllCallbackRegister call) or a Ptr (the return type from DllCallbackGetPtr) and use them instead.

**Comment by mlipok** [comment]
Did you try with recent beta ?

**Comment by genius257** [comment]
> 
> 
> Did you try with recent beta ?

Yes, the count does go a little higher, but same result.
Also beta releases are something i try to avoid depending on, as they have possible instabilities.

**Comment by genius257** [comment]
So it's fixed when using the default parameters.
Another solution would be a map with the function names as the key and the DllCallback as the value.
But map is not out of beta yet, and using array as a substitute would be too slow.

The current solution ran the following without problems:
```autoit
#include "AutoItObject_Internal.au3"

For $i=0 To 1000000
    If Mod($i, 1000) = 0 Then ConsoleWrite($i&@CRLF)
    $o = IDispatch()
Next

```
